# This file was generatered by Ferrite Configen.
from __future__ import annotations

from ferrite.codegen.types import Value

Point = int
DAC_COUNT: int = ...
ADC_COUNT: int = ...
SAMPLE_FREQ_HZ: int = ...
DAC_MAX_ABS_V: float = ...
ADC_MAX_ABS_V: float = ...
DAC_STEP_UV: float = ...
ADC_STEP_UV: float = ...
DAC_CODE_SHIFT: int = ...
MAX_APP_MSG_LEN: int = ...
MAX_MCU_MSG_LEN: int = ...
KEEP_ALIVE_PERIOD_MS: int = ...
KEEP_ALIVE_MAX_DELAY_MS: int = ...
